/* This file was generated by syncqt. */
#ifndef QT_QTWIDGETS_VERSION_H
#define QT_QTWIDGETS_VERSION_H

#define QTWIDGETS_VERSION_STR "5.7.1.1"

#define QTWIDGETS_VERSION 0x05070101
#endif // QT_QTWIDGETS_VERSION_H
